# Linux Build and Test
# Only run when pushed not main

name: Test
on:
  
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ci.yml'
    
permissions:
  contents: read

jobs:
  build-test:
    permissions:
      contents: write       # for actions/upload-release-asset to upload release asset
    runs-on: ubuntu-latest
    
    env:
      PROJECT_NAME: space-pixel-game
      PROJECT_BUILD_PATH: build
      PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}_dev_linux_x64
      PROJECT_CUSTOM_FLAGS: ""
      PROJECT_RESOURCES_PATH: resources

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.1

      - name: Cache build/_deps
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/build/_deps
          key: ${{ matrix.os }}-build-deps
          restore-keys: ${{ matrix.os }}-build-deps

      - name: Setup Environment
        run: | 
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev cmake
          mkdir -p ${{ env.PROJECT_RELEASE_PATH }}/${{ env.PROJECT_RESOURCES_PATH }}
        shell: bash

      - name: Configure Project
        run: |
          make configure

      - name: Build Project
        run: |
          make build PLATFORM=PLATFORM_DESKTOP BUILD_MODE=RELEASE PROJECT_CUSTOM_FLAGS=${{ env.PROJECT_CUSTOM_FLAGS }}
      - name: Test Project
        run: |
          make test

      - name: Create success artifact if tests pass
        if: success()
        run: |
          mkdir -p test-artifacts
          echo "success" > test-artifacts/success.txt
        shell: bash

      - name: Upload success artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-success
          path: test-artifacts
