name: Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    # - 'src/**' Disable rebuild on src changes
      - '.github/workflows/windows.yml'
    
permissions:
  contents: read

jobs:
  build-windows:
    permissions:
      contents: write       # for actions/upload-release-asset to upload release asset
    runs-on: windows-2022
    
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }} # Needs to be added through github
      BUILD_TYPE: Release

    steps:
      - uses: actions/checkout@v4

      - name: Cache build/_deps
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/build/_deps
          key: ${{ matrix.os }}-build-deps
          restore-keys: ${{ matrix.os }}-build-deps

      - name: Cache build/lib
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/build/lib
          key: ${{ matrix.os }}-build-lib
          restore-keys: ${{ matrix.os }}-build-lib

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: powershell
        working-directory: ${{github.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake $env:GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$env:BUILD_TYPE -DPLATFORM=Desktop

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: powershell
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --config $env:BUILD_TYPE

      # - name: Test
      #   working-directory: ${{github.workspace}}/build
      #   shell: powershell
      #   # Execute tests defined by the CMake configuration.
      #   # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #   run: ctest -C $env:BUILD_TYPE

      - name: Download + Authorize Butler
        run: |
            curl.exe -L -o butler.zip https://broth.itch.zone/butler/windows-amd64/15.24.0/archive/default
            7z x .\butler.zip
            .\butler.exe -V

      - name: Login To Butler
        run: .\butler.exe login

      - name: Push Windows to Itch
        run: .\butler.exe push build\space-pixel-game\Release maiconspas/spacegame:windows